---
title: "04_trophic_niches_from_stomach_contents"
author: "Peter Flood"
date: "2025-09-08"
output:
  html_document:
    toc: yes
    df_print: paged
  html_notebook:
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Install libraries 
```{r}
if (!require("openxlsx")) install.packages("openxlsx")
if (!require("SIBER")) install.packages("SIBER")
if (!require("coda")) install.packages("coda")
if (!require("ggpubr")) install.packages("ggpubr")
if (!require("ellipse")) install.packages("ellipse")
if (!require("tidyverse")) install.packages("tidyverse")
```

# Load libraries
```{r}
library(SIBER)
library(openxlsx)
library(coda)
library(ggpubr)
library(ellipse)
library(tidyverse)
```

# Load and format data

Load data
```{r}
post.consumer.nmds <- read.csv("Outputs/Stomach Contents/Diet/post_nmds_consumers.csv")
```

Format data
```{r}
#unite habitat and season columns to form community variable
stomach.habitat.season <- post.consumer.nmds %>% 
  filter(size_class %in% c(
    "N.flo1", 
    "N.vir1",
    "P.axa1",
    "R.gry1",
    "R.gry2",
    "S.lac1"
  )) %>% 
  unite(col = "community", Slough, Habitat, Season) %>% 
  rename(group = size_class, iso1 = MDS1, iso2 = MDS2) %>% 
  select(-c(ID))

#dropping size classes where n < 3 for a slough-habitat-season level
siber.data <- stomach.habitat.season %>% 
  select(iso1, iso2, group, community) %>% 
  group_by(group, community) %>% 
  filter(n()>2, sd(iso1)!=0, sd(iso2)!=0, !is.na(iso1), !is.na(iso2)) %>% 
  ungroup() %>% 
  as.data.frame() %>% 
  arrange(community, group)

#create object that has dropped groups (not all rows that were dropped)
removed.consumers <- stomach.habitat.season[!(stomach.habitat.season$group %in% siber.data$group),]
```

Create SIBER object, example sample sizes
```{r}
#createSiberObject
global.siber <- createSiberObject(siber.data)

#write out table of sample sizes
write.csv(global.siber[["sample.sizes"]] %>% t(), "Outputs/Stomach Contents/Trophic Niche/siber_global_n_table_stomachs.csv")
```
Visualize SIBER object
```{r}
# Create lists of plotting arguments to be passed onwards to each 
# of the three plotting functions.
community.hulls.args <- list(col = 1, lty = 1, lwd = 1)
group.ellipses.args  <- list(n = 100, p.interval = 0.95, lty = 1, lwd = 2)
group.hull.args      <- list(lty = 2, col = "grey20")

par(mfrow=c(1,1))
plotSiberObject(global.siber,
                ax.pad = 2, 
                hulls = F, community.hulls.args, 
                ellipses = T, group.ellipses.args,
                group.hulls = T, group.hull.args,
                bty = "L",
                iso.order = c(1,2),
                xlab = expression(d13C),
                ylab = expression(d15N)
)
```
## Calculate TA, SEA, and SEAc
```{r}
global.ML <- groupMetricsML(global.siber)
print(global.ML)
write.csv(t(global.ML), file = "Outputs/Stomach Contents/Trophic Niche/all_spp_ML_stomachs.csv")
```

## Calculate Layman metrics
```{r}
#calculate Layman metrics
post.layman.metrics <- communityMetricsML(global.siber)
```

## SIBER model
Set up model parameters
```{r}
#set up the model parameters 
# options for running jags
parms <- list()
parms$n.iter <- 2 * 10^6   # number of iterations to run the model for
parms$n.burnin <- 1 * 10^4 # discard the first set of values
parms$n.thin <- 100     # thin the posterior by this many
parms$n.chains <- 2        # run this many chains
parms$save.output = T
parms$save.dir = getwd()

# define the priors
priors <- list()
priors$R <- 1 * diag(2)
priors$k <- 2
priors$tau.mu <- 1.0E-3
```

Run SIBER model
```{r}
# fit the ellipses which uses an Inverse Wishart prior
# on the covariance matrix Sigma, and a vague normal prior on the 
# means. Fitting is via the JAGS method.
global.ellipses.posterior <- siberMVN(global.siber, parms, priors)

#calculate posterior estimates of ellipses for all groups
SEA.B<-siberEllipses(global.ellipses.posterior)
colnames(SEA.B)<-names(global.ellipses.posterior)
```

### Extract SIBER output
```{r}
#calculate credibility intervals
cr.p<-c(0.5, 0.95, 0.99) #vector of desired quantiles

#call hdrcde_hdr using lapply()
SEA.B.credibles<-lapply(
  as.data.frame(SEA.B), 
  function(x,...){tmp<-hdrcde::hdr(x)$hdr},
  prob = cr.p)

#match up group names
names(SEA.B.credibles)<-colnames(global.ML)

#this carries through the row names from matrices in SEA.B.credibles
#they don't turn out all that clean though, so adding a column later with the same info
y <- do.call(function(...) {
  tmp <- plyr::rbind.fill.matrix(...)
  rownames(tmp) <- sapply(SEA.B.credibles, function(i) {
    rownames(i)
  })
  return(tmp)
}, SEA.B.credibles)

y

#object with cleaned-up row names
interval<-rep(c("99%", "95%", "50%"), 134)

#replicated each name three times in sequence to match up with new data frame
seab.names<-data.frame(rep(names(SEA.B.credibles), each = 3))
colnames(seab.names)<-"names"

#seab.names<-separate(seab.names, col = names, into = c('hab.season', 'spp'), extra = "merge")

#combine names with new data frame
seab.cred.matrix<-data.frame(seab.names, interval, y)
colnames(seab.cred.matrix)<-c(colnames(seab.names), "interval", "lower", "upper")

#write out to a csv
write.csv(seab.cred.matrix, file = "Outputs/Stomach Contents/Trophic Niche/global.sc.SEA.B.credibles.csv")

# do similar to get the modes, taking care to pick up multimodal posterior
# distributions if present
SEA.B.modes<-lapply(
  as.data.frame(SEA.B), 
  function(x,...){tmp<-hdrcde::hdr(x)$mode},
  prob = cr.p, all.modes=T)

#need to do the same as for the credible intervals to get the colnames to be
#the names not the numbers
write.csv(SEA.B.modes, file = "Outputs/Stomach Contents/Trophic Niche/global.sc.SEA.B.modes.csv")

#read back in
SEA.B.modes.matrix<-read.csv(file = "Outputs/Stomach Contents/Trophic Niche/global.sc.SEA.B.modes.csv", header = T, row.names = 1)

#change colnames
colnames(SEA.B.modes.matrix)<-colnames(global.ML)
#transpose this matrix
SEA.B.modes.matrix.t<-t(SEA.B.modes.matrix)
#change the name of what is now a single column to mode
colnames(SEA.B.modes.matrix.t)<-"mode"
#write out the final csv over the previous mode csv
write.csv(SEA.B.modes.matrix.t, file = "Outputs/Stomach Contents/Trophic Niche/global.sc.SEA.B.modes.csv")
```

### Visualize niches
```{r}
herp.ellipse.df <- siber.data %>% 
  filter(group %in% c("A.gry1", "N.flo1", "N.vir1", 
                      "R.gry1", "R.gry2", "S.lac1")) %>% 
  separate(community, into = c("Slough", "Habitat", "Season"), sep = "_") %>% 
  rename(Species = group) %>% 
  mutate(Species = case_when(
    Species == "A.gry1" ~ "Cricket Frog Tadpole",
    Species == "N.flo1" ~ "Florida Green Watersnake",
    Species == "N.vir1" ~ "Peninsula Newt",
    Species == "R.gry1" ~ "Pig Frog Tadpoles",
    Species == "R.gry2" ~ "Pig Frog",
    Species == "S.lac1" ~ "Greater Siren"
  ))

(herp.niche.plot <- ggplot(data = herp.ellipse.df, aes(x = iso1, y = iso2, color = Species, fill = Species))+
    scale_color_viridis_d(end = 0, begin = 0.8, option = "A")+
    scale_fill_viridis_d(end = 0, begin = 0.8, option = "A")+
    facet_grid(Season~Habitat)+
    stat_conf_ellipse(level = 0.95, geom = "polygon", alpha = 0.5)+
    geom_point()+
    #labs(x = "δ13C(‰)", y = "δ15N(‰)")+
    labs(y = "MDS2", x = "MDS1")+
    theme_bw()+
    theme(text = element_text(family = "Times", size = 12),
          #panel.spacing.x = unit(7, "mm"),
          panel.grid.major = element_blank(),panel.grid.minor = element_blank(),
          strip.text.y.right = element_text(angle = 0),
          axis.text = element_text(size = 12))
  
)

ggsave("Figures/Stomach Contents/Trophic Niche/herp_stomachs_niche_plot.tiff", 
       herp.niche.plot, 
       height = 150, width = 200, units = "mm", dpi = 600)
```
Posterior mean ellipses
```{r}
mean_ellipses <- lapply(names(global.ellipses.posterior), function(name) {
  posterior <- global.ellipses.posterior[[name]] %>% as.data.frame()
  #colnames(posterior) <- c("Sigma211", "Sigma212", "Sigma221", "Sigma222", "mu1", "mu2")
  # Use backticks for column names with [ or ] characters
  mu_mean <- c(mean(posterior$`mu[1]`), mean(posterior$`mu[2]`))
  Sigma_mean <- matrix(
    c(
      mean(posterior$`Sigma2[1,1]`),
      mean(posterior$`Sigma2[1,2]`),
      mean(posterior$`Sigma2[2,1]`),
      mean(posterior$`Sigma2[2,2]`)
    ),
    nrow = 2, byrow = TRUE
  )
  ell <- ellipse(Sigma_mean, centre = mu_mean, level = 0.4, npoints = 100)
  df_ell <- as.data.frame(ell)
  df_ell$group_comm <- name
  df_ell$group <- sub("\\..*", "", name)
  df_ell$community <- sub(".*\\.", "", name)
  df_ell
})

mean_ellipses_df <- do.call(rbind, mean_ellipses) %>% 
  rename(community = group, group = community) %>% 
  mutate(group = factor(group))
```

Ellipse Cloud Plot
```{r}
n_ellipses <- 200

ellipse_clouds <- list()

for (name in names(global.ellipses.posterior)) {
  posterior <- global.ellipses.posterior[[name]]
  nrow_posterior <- nrow(posterior)
  set.seed(2024)
  sampled_rows <- sample(seq_len(nrow_posterior), n_ellipses)
  
  temp <- lapply(sampled_rows, function(i) {
    row <- posterior[i, ]
    mu <- c(row[["mu[1]"]], row[["mu[2]"]])
    # Make sure you get the elements in the correct order:
    Sigma <- matrix(
      c(row[["Sigma2[1,1]"]], row[["Sigma2[1,2]"]],
        row[["Sigma2[2,1]"]], row[["Sigma2[2,2]"]]),
      nrow = 2, byrow = TRUE
    )
    ell <- ellipse(Sigma, centre = mu, level = 0.40, npoints = 100)
    df <- as.data.frame(ell)
    df$group_comm <- name
    df$draw <- i
    df
  })
  ellipse_clouds[[name]] <- do.call(rbind, temp)
}

ellipse_cloud_df <- do.call(rbind, ellipse_clouds)

ellipse_cloud_df$community <- sub("\\..*", "", ellipse_cloud_df$group_comm) %>% factor()
ellipse_cloud_df$group <- sub(".*\\.", "", ellipse_cloud_df$group_comm) %>% 
  factor() 
```

Plot Ellipse Cloud
```{r}
#Format data for plotting
siber.plot.data <- siber.data %>%
      mutate(Species = group,
        Species = if_else(
        Species == "R.gry1", "Pig Frog Tadpole", "Greater Siren"
      )) %>% 
  separate(community, into = c("Slough", "Habitat", "Season"), sep = "_")

ellipse.cloud.df <- ellipse_cloud_df %>%
        mutate(Species = group,
          Species = if_else(
          Species == "gry1", "Pig Frog Tadpole", "Greater Siren"
        )) %>% 
  separate(community, into = c("Slough", "Habitat", "Season"), sep = "_")
  
mean.ellipses.df <- mean_ellipses_df %>%
        mutate(Species = group,
          Species = if_else(
          Species == "gry1", "Pig Frog Tadpole", "Greater Siren"
        )) %>% 
  separate(community, into = c("Slough", "Habitat", "Season"), sep = "_") 
  

(
  ellipse.cloud.plot <- ggplot(
    siber.plot.data,
    aes(
      x = iso1,
      y = iso2,
      color = Species,
      fill = Species
    )
  ) +
    geom_path(
      data = ellipse.cloud.df,
      aes(
        x = x,
        y = y,
        group = interaction(group_comm, draw),
        color = Species
      ),
      size = 0.7,
      alpha = 0.15,
      show.legend = FALSE
    ) +
    geom_path(
      data = mean.ellipses.df,
      aes(
        x = x,
        y = y,
        group = group_comm,
        color = Species
      ),
      #color = "red",
      linetype = "dashed",
      size = 1.2,
      show.legend = FALSE
    ) +
    stat_conf_ellipse(
      level = 0.95,
      geom = "polygon",
      alpha = 0.5
    ) +
    geom_point(size = 3, alpha = 0.8) +
    labs(
      title = "Trophic Niches from Stomach Contents",
      x = "MDS1",
      y = "MDS2",
      color = "Species",
      fill = "Species"
    ) +
    scale_color_viridis_d(
      end = 0,
      begin = 0.8,
      option = "A"
    ) +
    scale_fill_viridis_d(
      end = 0,
      begin = 0.8,
      option = "A"
    ) +
    facet_grid(Season ~ Habitat) +
    theme_bw() +
    coord_fixed(xlim = c(-1, 1), ylim = c(-1, 1.5))
)

ggsave("Figures/Stomach Contents/Trophic Niche/herp_stomachs_poster_niches_plot.tiff", 
       ellipse.cloud.plot, 
       height = 150, width = 200, units = "mm", dpi = 600)
```
